---
- name: to install httpd in webservers and apache2 in dbservers
  hosts: all
  become: true
  tasks:
  - name: install httpd in webservers
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache

  - name: install apache2 in dbservers
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache

  - name: start apache service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"  
    tags: start_apache

  - name: copy index.html to /var/www/html
    copy:
      src: /home/ansadmin/ansible_tasks/index.html
      dest: /var/www/html
      mode: 0666
    tags: copy_file


