---
- name: this is a playbook to create a file
  hosts: all
  become: true
  vars_files:
  - file.yml
  tasks:
  - name: create file test
    file:
       path: "{{ file }}"
       state: touch
       mode: 0666

