---
- name: need to install apache on ubuntu
  hosts: dbservers
  become: true
  tasks:
  - name: install apache
    service:
      name: apache2
      state: stopped

  - name: start service apache
    apt:
      name: apache2
      state: absent
