---
- name: multi package install
  hosts: webservers
  become: true
  tasks:
  - name: install multi package
    yum:
      name: ['git', 'tree', 'telnet', 'gzip', 'make', 'gcc']
      state: installed

