---
- name: to install httpd in webservers and apache2 in dbservers
  hosts: all
  become: true
  vars:
    port: 8082
  tasks:
  - name: install httpd in webservers
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache
    notify: start httpd service

  - name: install apache2 in dbservers
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache
    notify: start apache service

  - name: copy index.html to /var/www/html
    copy:
      src: /home/ansadmin/ansible_tasks/index.html
      dest: /var/www/html
      mode: 0666
    tags: copy_file 
  
  - name: change httpd port to 8082
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart httpd service
    
  - name: change apache port to 8082
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '# /etc/apache2/sites-enabled/000-default.conf'
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache service

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
    tags: start_apache
    
  - name: start apache service
    service:
      name: apache2
      state: started
    tags: start_apache2

  - name: restart httpd service
    service:
      name: httpd
      state: restarted
    tags: restart_httpd

  - name: restart apache service
    service: 
      name: apache2
      state: started


